version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
    target-branch: main
    labels:
      - dependabot
    open-pull-requests-limit: 10
    commit-message:
      prefix: BAU
    groups:
      testing:
        patterns:
          - "mocha"
          - "chai*"
          - "sinon*"
          - "nyc"
          - "@cucumber/*"
          - "@playwright/*"
          - "playwright-core"
          - "@axe-core/*"
          - "wiremock"
          - "js-yaml"
          - "dotenv-cli"
          - "npm-run-all"
      linting-and-formatting:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "prettier*"
          - "globals"
      build-tools:
        patterns:
          - "sass"
          - "uglify-js"
          - "nodemon"
          - "dotenv"
      express:
        patterns:
          - "express"
          - "express-*"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
    target-branch: main
    labels:
      - dependabot
    commit-message:
      prefix: BAU
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
    target-branch: main
    labels:
      - dependabot
    commit-message:
      prefix: BAU
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: pre-commit
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
    target-branch: main
    labels:
      - dependabot
    commit-message:
      prefix: BAU
    groups:
      pre-commit-hooks:
        patterns:
          - "*"
